repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.4.2'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["--without-hashes", "-f", "requirements.txt", "-o", "requirements.txt"]
